name: On deploy to Master Branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Check cache for node modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-deps-${{ hashFiles('yarn.lock') }}
    - name: Yarn Install
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: |
        yarn install
    - name: Type check
      run: |
        yarn type-check
    - name: Tests
      run: |
        yarn test --watchAll=false
    - name: Production Build
      run: |
        yarn build
    - name: Deploy to S3
      run: |
        yarn deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
